Button new_instance_button;

Textbox new_instance_name_textbox;
Button create_button;
Button instance_creation_cancel;

TransparrentBackground last_played_bg;
Button launch_last_instance_button;

TransparrentBackground categories_bg;
Button MainCategory_button;
Button InstancesCategory_button;
Button SettingsCategory_button;
Button SavesToolCategory_button;

TransparrentBackground settings_bg;

Button Subcat_settings_main_button;

Textbox SlimeRancher_steam_path_textbox;
Textbox SlimeRancher_instances_path_textbox;
Button SaveConfig_button;
Checkbox Show_older_instances_checkbox;
Checkbox Show_moded_instances_checkbox;

Button Subcat_settings_progile_button;

Textbox SteamProfile_name_textbox;
Textbox SteamProfile_password_textbox;
Button save_profile_button;
Checkbox login_manualy_checkbox;
sf::Text Profile_warning_text;

TransparrentBackground instances_bg;


TransparrentBackground datatools_bg;